dataset: celeb_a
epochs: 10
global_batch_size: 32

model_overrides:
  gen:
    image_res: 64
    blocks:
      - channels: 256
        kernel_size: 4
        stride: 1
        padding: VALID
      - channels: 128
        kernel_size: 4
        stride: 2
        padding: SAME
      - channels: 64
        kernel_size: 4
        stride: 2
        padding: SAME
      - channels: 32
        kernel_size: 4
        stride: 2
        padding: SAME
