defaults:
  - model: thermo_kaem
  - training: cifar10
  - _self_

model:
  z_dim: 41
  seed: 0

  ebm:
    layer_widths: [100, 100, 1]
    leakyrelu_leak: 0.1
    p0_stddev: 1.0
    mcmc:
      stepsize: 0.16
      numsteps: 60
    optim:
      lr_init: 0.00002
      lr_end: 0.00002
      lr_decay: 1.0
      beta1: 0.999
      beta2: 0.5

  gen:
    gaussian_stddev: 0.3
    leakyrelu_leak: 0.2
    img_channels: 3
    batchnorm: True
    mcmc:
      stepsize: 0.01
      numsteps: 20
    optim:
      lr_init: 0.0001
      lr_end: 0.0001
      lr_decay: 1.0
      beta1: 0.999
      beta2: 0.5

  kaem:
    mixture: true
    numquad: 100
    numgrid: 10
    kan:
      basis: chebyshev
      chebyshev:
        D: 5
      grid_updating:
        numgrid: 10
        update_frequency: 100
        frequency_decay: 0.998

run_name: ${model.base}_${training.dataset}

logging:
  logdir: runs/${run_name}
  ckpt_dir: runs/${run_name}
  ckpt_every: 20
  sample_every: 1
  num_samples: 100

lr_schedule:
  epoch_begin: 0
  epoch_step: 0

unbiased_metrics:
  batch_size_to_generate: 50
  num_samples: 20000
  regression_steps: [2000, 4000, 6000, 8000, 10000, 12000, 14000, 16000, 18000, 20000]
