ebm:
  energy_dim = 100
  leakyrelu_leak = 0.1
  p0_stddev = 1.0
  nuts_eta = 0.16
  nuts_burn_in = 20
  nuts_numsteps = 60
  lr_init = 0.00002
  lr_end = 0.00001
  lr_decay = 0.975
  beta1 = 0.999
  beta2 = 0.5

gen:
  energy_dim = 100
  img_channels = 3
  image_res = 32
  leakyrelu_leak = 0.2
  gaussian_stddev = 0.3
  nuts_eta = 0.01
  nuts_burn_in = 20
  nuts_numsteps = 20
  lr_init = 0.0001
  lr_end = 0.00005
  lr_decay = 0.975
  beta1 = 0.999
  beta2 = 0.5

model:
  z_dim = 80

thermo:
  num_temps = 10
  xchange_every = 2

training:
  epochs=5
  dataset = "cifar10"
  batch_size = 128

lr_schedule:
  begin = 1
  step = 1 

logging:
  logdir = "logs/thermo/cifar10/"
  ckpt_dit = "logs/thermo/cifar10/"
  ckpt_every = 2
  eval_every = 2
  sample_every = 2
  num_samples = 100

unbiased_metrics:
  batch_size_to_generate = 2000
  num_samples = 20000
  regression_steps = 2000, 4000, 6000, 8000, 10000, 12000, 14000, 16000, 18000, 20000
