model:
  z_dim: 8
  seed: 0
  base: kaem

  ebm:
    layer_widths: [200, 200, 1]
    leakyrelu_leak: 0.1
    p0_stddev: 1.0
    mcmc:
      stepsize: 0.01
      numsteps: 5
    optim:
      lr_init: 1e-3
      lr_end: 1e-4
      lr_decay: 0.975
      beta1: 0.999
      beta2: 0.5

  gen:
    gaussian_stddev: 0.3
    leakyrelu_leak: 0.1
    blocks:
      - channels: 16
        kernel_size: 4
        stride: 1
        padding: VALID
      - channels: 8
        kernel_size: 4
        stride: 2
        padding: SAME
      - channels: 4
        kernel_size: 4
        stride: 2
        padding: SAME
    img_channels: 3
    image_res: 32
    mcmc:
      stepsize: 0.01
      numsteps: 5
    optim:
      lr_init: 1e-3
      lr_end: 1e-4
      lr_decay: 0.975
      beta1: 0.999
      beta2: 0.5

  kaem:
    mixture: true
    numquad: 25
    numgrid: 10
    kan:
      basis: spline
      spline:
        k: 3
        G: 10
      grid_updating:
        numgrid: 10
        update_frequency: 2
        frequency_decay: 0.98

  thermo:
    num_temps: 4
    xchange_every: 2

training:
  epochs: 1
  batch_size: 32
  dataset: fake32

logging:
  logdir: /tmp
  ckpt_dir: /tmp
  ckpt_every: 1
  eval_every: 1
  sample_every: 1
  num_samples: 10

lr_schedule:
  epoch_begin: 0
  epoch_step: 1

unbiased_metrics:
  batch_size_to_generate: 50
  num_samples: 50
  regression_steps: [1000, 1200, 1300]


